### ISSUE TITLE
报跨域了，大佬看看

### ISSUE THREAD

**Issue by binyellow** [sh-winter/vite-plugin-qiankun#1]
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/29519985/160045910-9a0479d1-aa63-4385-8039-cd8d90bec51f.png">

**Comment by sh-winter** [comment]
看起来子应用没有启动成功呀，你是怎么运行的？我试着直接 `clone` 下来，然后运行 `yarn && yarn example`，是可以正常启动的

**Comment by sh-winter** [comment]
> <img alt="image" width="1647" src="https://user-images.githubusercontent.com/29519985/160045910-9a0479d1-aa63-4385-8039-cd8d90bec51f.png">

看起来子应用没有启动成功呀，你是怎么运行的？我试着直接 `clone` 下来，然后运行 `yarn && yarn example`，是可以正常启动的

**Comment by lianzujiao** [comment]
> > <img alt="image" width="1647" src="https://user-images.githubusercontent.com/29519985/160045910-9a0479d1-aa63-4385-8039-cd8d90bec51f.png">
> 
> 看起来子应用没有启动成功呀，你是怎么运行的？我试着直接 `clone` 下来，然后运行 `yarn && yarn example`，是可以正常启动的

根据qiankuan 官网，主应用和子应用不在同一域名下，可以使用nginx代理
