### ISSUE TITLE
大佬冒昧的问现在用你这个项目会有什么坑吗？

### ISSUE THREAD

**Issue by wanliyunyan** [sh-winter/vite-plugin-qiankun#2]
我这公司准备搞vite2+vue3的微前端项目了，正好看到了你这项目，所以冒昧的问一下，一旦走上这条不归路，会有什么大坑吗？

**Comment by sh-winter** [comment]
这个项目是我在上家公司时开发的，当时有这个需求，所以开了这个项目，但是现在由于一些不好的原因，我离职了，所以也只能是业余时间来维护，不推荐你在生产环境使用，其实这个项目的实现是不好的，与 `vite` 内部的处理逻辑有耦合，随着 `vite` 的更新，可能就不能用了

**Comment by sh-winter** [comment]
`vite` 最终应该会自带动态 `public path` 的支持，这只是个过渡的产物

**Comment by wanliyunyan** [comment]
哦哦 谢谢了那就不用了
